- name: coyote
  title: kafka-connect-blockchain

- name: Run PODs
  entries:
    - name: Deploy Blockchain and Fast Data Dev
      command: kubectl apply -f ci/deployment.yaml
    - name: Wait for Connect to get up
      command: >
        bash -c '
          for ((i=0;i<30;i++)); do
            sleep 5;
            POD=`kubectl get pods --field-selector=status.phase=Running -l=app=test-kafka-connect-blockchain -o jsonpath='{.items[0].metadata.name}'`
            kubectl exec $POD -c kafka -- curl "http://localhost:8083/connectors" && break;
          done'
      nolog: true

- name: coyote
  vars:
    POD_NAME: kubectl get pods --field-selector=status.phase=Running -l=app=test-kafka-connect-blockchain -o jsonpath='{.items[0].metadata.name}'

- name: Prepare Blockchain
  entries:   
    - name: Create Topic
      command: >-
        bash -c '
          POD=`%POD_NAME%`
          kubectl exec -i $POD -c kafka -- kafka-topics --zookeeper $ADV_HOST:2181 --topic blockchain --partitions 1 --replication-factor 1 --create'

- name: Deploy Helm Blockchain Distributed Connector
  entries:   
    - name: Run helm chart
      command: > 
        helm install -f ci/values.yaml .
    - command: sleep 125
      nolog: true

- name: Test Blockchain
  entries:
    - name: Write Entries into Topic
      command: >-
        bash -c '
          POD=`%POD_NAME%`
          kubectl exec -i $POD -c kafka -- kafka-avro-console-consumer --bootstrap-server localhost:9092 --topic blockchain --from-beginning'
      ignore_exit_code: true
      stdout_has: [ 'lock_time', 'sequence', '"tx_index":[0-9]{5,5}' ]
      timeout: 45s

- name: Cleanup K8
  entries:   
    - name: Delete Deployments
      command: >
        kubectl delete deployments --all
    - name: Delete Stateful Apps
      command: >
        kubectl delete statefulsets.apps --all
    - name: Delete Service
      command: >
        kubectl delete services --all
